const rows = [
[1,1,"Production","production","sản xuất"],
[2,1,"Production","production line","dây chuyền sản xuất"],
[3,1,"Production","production plan","kế hoạch sản xuất"],
[4,1,"Production","production schedule","lịch sản xuất"],
[5,1,"Production","production target","mục tiêu sản xuất"],
[6,1,"Production","production output","sản lượng sản xuất"],
[7,1,"Production","production volume","khối lượng sản xuất"],
[8,1,"Production","production capacity","năng lực sản xuất"],
[9,1,"Production","production rate","tốc độ sản xuất"],
[10,1,"Production","production cycle","chu kỳ sản xuất"],
[11,1,"Production","production shift","ca sản xuất"],
[12,1,"Production","shift handover","bàn giao ca"],
[13,1,"Production","work order","lệnh sản xuất"],
[14,1,"Production","job order","lệnh công việc"],
[15,1,"Production","batch","mẻ/lô sản xuất"],
[16,1,"Production","lot","lô sản xuất"],
[17,1,"Production","pilot run","chạy thử nghiệm"],
[18,1,"Production","mass production","sản xuất hàng loạt"],
[19,1,"Production","trial production","sản xuất thử"],
[20,1,"Production","ramp-up","giai đoạn tăng sản lượng"],
[21,1,"Production","line start-up","khởi động dây chuyền"],
[22,1,"Production","line shutdown","dừng dây chuyền"],
[23,1,"Production","line clearance","xác nhận làm sạch dây chuyền"],
[24,1,"Production","line balancing","cân bằng chuyền"],
[25,1,"Production","bottleneck","điểm nghẽn"],
[26,1,"Production","workstation","trạm làm việc"],
[27,1,"Production","operator","công nhân vận hành"],
[28,1,"Production","technician","kỹ thuật viên"],
[29,1,"Production","supervisor","giám sát viên"],
[30,1,"Production","shift leader","trưởng ca"],
[31,1,"Production","headcount","số lượng nhân lực"],
[32,1,"Production","manpower","nhân lực"],
[33,1,"Production","labor productivity","năng suất lao động"],
[34,1,"Production","productivity","năng suất"],

[35,2,"Production","throughput","lưu lượng/sản lượng qua công đoạn"],
[36,2,"Production","cycle time","thời gian chu kỳ"],
[37,2,"Production","takt time","nhịp sản xuất theo nhu cầu"],
[38,2,"Production","lead time","thời gian từ đầu đến cuối"],
[39,2,"Production","uptime","thời gian máy hoạt động"],
[40,2,"Production","downtime","thời gian dừng máy"],
[41,2,"Production","idle time","thời gian nhàn rỗi"],
[42,2,"Production","changeover time","thời gian chuyển đổi mã hàng"],
[43,2,"Production","setup time","thời gian thiết lập"],
[44,2,"Production","work in process","bán thành phẩm đang xử lý"],
[45,2,"Production","finished goods","thành phẩm"],
[46,2,"Production","raw material","nguyên vật liệu"],
[47,2,"Production","semi-finished product","bán thành phẩm"],
[48,2,"Production","scrap","phế phẩm"],
[49,2,"Production","rework","hàng sửa lại/công việc sửa lại"],
[50,2,"Production","yield","tỷ lệ đạt"],
[51,2,"Production","first pass yield","tỷ lệ đạt ngay lần đầu"],
[52,2,"Production","line efficiency","hiệu suất dây chuyền"],
[53,2,"Production","capacity utilization","mức sử dụng công suất"],
[54,2,"Production","production loss","tổn thất sản xuất"],
[55,2,"Production","yield loss","tổn thất do giảm yield"],
[56,2,"Production","output gap","chênh lệch sản lượng"],
[57,2,"Production","production constraint","ràng buộc sản xuất"],
[58,2,"Production","production priority","ưu tiên sản xuất"],
[59,2,"Production","urgent order","đơn hàng khẩn"],
[60,2,"Production","backlog","khối lượng công việc tồn"],
[61,2,"Production","meet the target","đạt mục tiêu"],
[62,2,"Production","increase output","tăng sản lượng"],
[63,2,"Production","reduce downtime","giảm thời gian dừng máy"],
[64,2,"Production","balance the line","cân bằng dây chuyền"],
[65,2,"Production","monitor production","theo dõi sản xuất"],
[66,2,"Production","track output","theo dõi sản lượng"],
[67,2,"Production","recover production","khôi phục sản xuất"],
[68,2,"Production","resume production","tiếp tục sản xuất"],

[69,3,"Production","stop the line","dừng dây chuyền"],
[70,3,"Production","run at full capacity","chạy hết công suất"],
[71,3,"Machine","machine","máy móc"],
[72,3,"Machine","equipment","thiết bị"],
[73,3,"Machine","fixture","đồ gá"],
[74,3,"Machine","jig","đồ gá định vị"],
[75,3,"Machine","tooling","dụng cụ/đồ nghề sản xuất"],
[76,3,"Machine","component","linh kiện/bộ phận"],
[77,3,"Machine","assembly","cụm lắp ráp"],
[78,3,"Machine","mechanism","cơ cấu"],
[79,3,"Machine","actuator","cơ cấu chấp hành"],
[80,3,"Machine","sensor","cảm biến"],
[81,3,"Machine","photoelectric sensor","cảm biến quang"],
[82,3,"Machine","proximity sensor","cảm biến tiệm cận"],
[83,3,"Machine","pressure sensor","cảm biến áp suất"],
[84,3,"Machine","temperature sensor","cảm biến nhiệt độ"],
[85,3,"Machine","load cell","cảm biến lực"],
[86,3,"Machine","encoder","bộ mã hóa"],
[87,3,"Machine","motor","động cơ"],
[88,3,"Machine","servo motor","động cơ servo"],
[89,3,"Machine","stepper motor","động cơ bước"],
[90,3,"Machine","cylinder","xi lanh"],
[91,3,"Machine","pneumatic cylinder","xi lanh khí nén"],
[92,3,"Machine","solenoid valve","van điện từ"],
[93,3,"Machine","valve","van"],
[94,3,"Machine","regulator","bộ điều áp"],
[95,3,"Machine","filter","bộ lọc"],
[96,3,"Machine","nozzle","đầu phun/đầu hút"],
[97,3,"Machine","vacuum nozzle","đầu hút chân không"],
[98,3,"Machine","suction cup","cốc hút"],
[99,3,"Machine","conveyor","băng tải"],
[100,3,"Machine","roller","con lăn"],
[101,3,"Machine","bearing","vòng bi"],
[102,3,"Machine","shaft","trục"],

[103,4,"Machine","belt","dây đai"],
[104,4,"Machine","pulley","puly"],
[105,4,"Machine","gear","bánh răng"],
[106,4,"Machine","gearbox","hộp số"],
[107,4,"Machine","coupling","khớp nối"],
[108,4,"Machine","heater","bộ gia nhiệt"],
[109,4,"Machine","chiller","bộ làm lạnh"],
[110,4,"Machine","fan filter unit","bộ quạt lọc FFU"],
[111,4,"Machine","control panel","tủ/bảng điều khiển"],
[112,4,"Machine","PLC","bộ điều khiển logic khả trình"],
[113,4,"Machine","HMI","giao diện người-máy"],
[114,4,"Machine","alarm","cảnh báo"],
[115,4,"Machine","interlock","liên động an toàn"],
[116,4,"Machine","emergency stop","nút dừng khẩn cấp"],
[117,4,"Machine","setpoint","giá trị cài đặt"],
[118,4,"Machine","parameter","tham số"],
[119,4,"Machine","recipe","bộ công thức/cài đặt máy"],
[120,4,"Machine","machine setting","cài đặt máy"],
[121,4,"Machine","operating condition","điều kiện vận hành"],
[122,4,"Machine","machine condition","tình trạng máy"],
[123,4,"Machine","machine capability","năng lực máy"],
[124,4,"Machine","machine accuracy","độ chính xác của máy"],
[125,4,"Machine","machine repeatability","độ lặp lại của máy"],
[126,4,"Machine","machine stability","độ ổn định của máy"],
[127,4,"Machine","calibrate","hiệu chuẩn"],
[128,4,"Machine","adjust","điều chỉnh"],
[129,4,"Machine","align","căn chỉnh"],
[130,4,"Machine","reset","đặt lại/reset"],
[131,4,"Machine","restart","khởi động lại"],
[132,4,"Machine","initialize","khởi tạo"],
[133,4,"Machine","operate","vận hành"],
[134,4,"Machine","inspect the machine","kiểm tra máy"],
[135,4,"Machine","check the sensor","kiểm tra cảm biến"],
[136,4,"Machine","replace the part","thay thế linh kiện"],

[137,5,"Machine","tighten the bolt","siết bu lông"],
[138,5,"Machine","loosen the screw","nới vít"],
[139,5,"Machine","lubricate","bôi trơn"],
[140,5,"Machine","troubleshoot the machine","xử lý sự cố máy"],
[141,5,"Process","process","quy trình/công đoạn"],
[142,5,"Process","process flow","luồng quy trình"],
[143,5,"Process","process step","bước công đoạn"],
[144,5,"Process","process sequence","trình tự công đoạn"],
[145,5,"Process","process window","cửa sổ công nghệ"],
[146,5,"Process","process condition","điều kiện công nghệ"],
[147,5,"Process","process parameter","tham số công nghệ"],
[148,5,"Process","critical parameter","tham số trọng yếu"],
[149,5,"Process","control parameter","tham số kiểm soát"],
[150,5,"Process","standard condition","điều kiện tiêu chuẩn"],
[151,5,"Process","process specification","đặc tính/yêu cầu quy trình"],
[152,5,"Process","standard operating procedure","quy trình thao tác chuẩn"],
[153,5,"Process","work instruction","hướng dẫn công việc"],
[154,5,"Process","process sheet","phiếu/thông số công nghệ"],
[155,5,"Process","process recipe","công thức quy trình"],
[156,5,"Process","process setup","thiết lập quy trình"],
[157,5,"Process","process change","thay đổi quy trình"],
[158,5,"Process","process deviation","sai lệch quy trình"],
[159,5,"Process","process variation","biến động quy trình"],
[160,5,"Process","process capability","năng lực quá trình"],
[161,5,"Process","process stability","độ ổn định quá trình"],
[162,5,"Process","process control","kiểm soát quá trình"],
[163,5,"Process","process monitoring","theo dõi quá trình"],
[164,5,"Process","in-process inspection","kiểm tra trong công đoạn"],
[165,5,"Process","incoming process","công đoạn đầu vào"],
[166,5,"Process","upstream process","công đoạn phía trước"],
[167,5,"Process","downstream process","công đoạn phía sau"],
[168,5,"Process","bottleneck process","công đoạn nút thắt"],
[169,5,"Process","critical process","công đoạn trọng yếu"],
[170,5,"Process","manual process","công đoạn thủ công"],

[171,6,"Process","automated process","công đoạn tự động"],
[172,6,"Process","bonding","dán/ép liên kết"],
[173,6,"Process","lamination","cán/ép lớp"],
[174,6,"Process","coating","phủ lớp"],
[175,6,"Process","dispensing","bơm/định lượng vật liệu"],
[176,6,"Process","curing","đóng rắn"],
[177,6,"Process","baking","sấy/nung"],
[178,6,"Process","drying","làm khô"],
[179,6,"Process","cleaning","làm sạch"],
[180,6,"Process","washing","rửa"],
[181,6,"Process","cutting","cắt"],
[182,6,"Process","die cutting","dập cắt"],
[183,6,"Process","punching","đột/dập"],
[184,6,"Process","pressing","ép"],
[185,6,"Process","molding","đúc/tạo hình"],
[186,6,"Process","assembly process","công đoạn lắp ráp"],
[187,6,"Process","inspection process","công đoạn kiểm tra"],
[188,6,"Process","packing process","công đoạn đóng gói"],
[189,6,"Process","process input","đầu vào quá trình"],
[190,6,"Process","process output","đầu ra quá trình"],
[191,6,"Process","control limit","giới hạn kiểm soát"],
[192,6,"Process","upper limit","giới hạn trên"],
[193,6,"Process","lower limit","giới hạn dưới"],
[194,6,"Process","tolerance","dung sai"],
[195,6,"Process","process margin","biên an toàn của quy trình"],
[196,6,"Process","optimize the process","tối ưu quy trình"],
[197,6,"Process","standardize the process","tiêu chuẩn hóa quy trình"],
[198,6,"Process","validate the process","xác nhận hiệu lực quy trình"],
[199,6,"Process","verify the condition","xác minh điều kiện"],
[200,6,"Process","control the parameter","kiểm soát tham số"],
[201,6,"Process","monitor the trend","theo dõi xu hướng"],
[202,6,"Process","fine-tune the setting","tinh chỉnh cài đặt"],
[203,6,"Process","lock the parameter","khóa tham số"],
[204,6,"Process","change the recipe","thay đổi công thức"],

[205,7,"Process","follow the SOP","tuân thủ SOP"],
[206,7,"Process","skip a step","bỏ qua một bước"],
[207,7,"Process","repeat the process","lặp lại quy trình"],
[208,7,"Process","process out of control","quá trình mất kiểm soát"],
[209,7,"Process","within specification","nằm trong tiêu chuẩn"],
[210,7,"Process","out of specification","ngoài tiêu chuẩn"],
[211,7,"Material","material","vật liệu"],
[212,7,"Material","raw material property","tính chất nguyên vật liệu"],
[213,7,"Material","incoming material","vật liệu đầu vào"],
[214,7,"Material","consumable","vật tư tiêu hao"],
[215,7,"Material","adhesive","chất kết dính"],
[216,7,"Material","epoxy","keo epoxy"],
[217,7,"Material","resin","nhựa resin"],
[218,7,"Material","hardener","chất đóng rắn"],
[219,7,"Material","solvent","dung môi"],
[220,7,"Material","cleaning agent","chất làm sạch"],
[221,7,"Material","tape","băng dính"],
[222,7,"Material","release liner","lớp liner chống dính"],
[223,7,"Material","protective film","màng bảo vệ"],
[224,7,"Material","PET film","màng PET"],
[225,7,"Material","OCA","keo quang học OCA"],
[226,7,"Material","foam","mút/xốp"],
[227,7,"Material","rubber","cao su"],
[228,7,"Material","plastic","nhựa"],
[229,7,"Material","metal","kim loại"],
[230,7,"Material","stainless steel","thép không gỉ"],
[231,7,"Material","aluminum","nhôm"],
[232,7,"Material","glass","kính"],
[233,7,"Material","substrate","vật liệu nền"],
[234,7,"Material","coating layer","lớp phủ"],
[235,7,"Material","surface treatment","xử lý bề mặt"],
[236,7,"Material","material lot","lô vật liệu"],
[237,7,"Material","lot number","mã lô"],
[238,7,"Material","batch number","số mẻ"],

[239,8,"Material","shelf life","hạn sử dụng"],
[240,8,"Material","expiry date","ngày hết hạn"],
[241,8,"Material","storage condition","điều kiện bảo quản"],
[242,8,"Material","storage temperature","nhiệt độ bảo quản"],
[243,8,"Material","humidity requirement","yêu cầu độ ẩm"],
[244,8,"Material","material specification","đặc tính/yêu cầu vật liệu"],
[245,8,"Material","material property","tính chất vật liệu"],
[246,8,"Material","thickness","độ dày"],
[247,8,"Material","width","chiều rộng"],
[248,8,"Material","length","chiều dài"],
[249,8,"Material","hardness","độ cứng"],
[250,8,"Material","viscosity","độ nhớt"],
[251,8,"Material","adhesion","độ bám dính"],
[252,8,"Material","surface energy","năng lượng bề mặt"],
[253,8,"Material","transparency","độ trong suốt"],
[254,8,"Material","color variation","biến động màu sắc"],
[255,8,"Material","material traceability","khả năng truy xuất vật liệu"],
[256,8,"Material","certificate of analysis","chứng nhận phân tích COA"],
[257,8,"Material","material change","thay đổi vật liệu"],
[258,8,"Material","alternative material","vật liệu thay thế"],
[259,8,"Material","approved material","vật liệu đã phê duyệt"],
[260,8,"Material","material shortage","thiếu vật liệu"],
[261,8,"Material","material mismatch","nhầm/không khớp vật liệu"],
[262,8,"Material","material contamination","nhiễm bẩn vật liệu"],
[263,8,"Material","mix the material","trộn vật liệu"],
[264,8,"Material","store the material","bảo quản vật liệu"],
[265,8,"Material","issue material","cấp phát vật liệu"],
[266,8,"Material","verify the lot","xác minh lô vật liệu"],
[267,8,"Material","check the expiry date","kiểm tra hạn sử dụng"],
[268,8,"Material","quarantine the material","cách ly vật liệu"],
[269,8,"Material","replace the material","thay vật liệu"],
[270,8,"Material","change the epoxy lot","đổi lô epoxy"],
[271,8,"Defect","defect","lỗi/khuyết tật"],
[272,8,"Defect","defect rate","tỷ lệ lỗi"],

[273,9,"Defect","defect mode","dạng lỗi"],
[274,9,"Defect","defect type","loại lỗi"],
[275,9,"Defect","defect location","vị trí lỗi"],
[276,9,"Defect","defect size","kích thước lỗi"],
[277,9,"Defect","defect pattern","mẫu hình lỗi"],
[278,9,"Defect","defect distribution","phân bố lỗi"],
[279,9,"Defect","visual defect","lỗi ngoại quan"],
[280,9,"Defect","functional defect","lỗi chức năng"],
[281,9,"Defect","cosmetic defect","lỗi thẩm mỹ"],
[282,9,"Defect","critical defect","lỗi nghiêm trọng"],
[283,9,"Defect","major defect","lỗi chính"],
[284,9,"Defect","minor defect","lỗi nhẹ"],
[285,9,"Defect","scratch","vết xước"],
[286,9,"Defect","dent","vết lõm"],
[287,9,"Defect","crack","vết nứt"],
[288,9,"Defect","chip","mẻ cạnh"],
[289,9,"Defect","burr","ba via"],
[290,9,"Defect","stain","vết bẩn/ố"],
[291,9,"Defect","particle","hạt dị vật"],
[292,9,"Defect","contamination","nhiễm bẩn"],
[293,9,"Defect","dust","bụi"],
[294,9,"Defect","foreign material","dị vật"],
[295,9,"Defect","bubble","bóng khí"],
[296,9,"Defect","void","lỗ rỗng/khoảng trống"],
[297,9,"Defect","delamination","tách lớp"],
[298,9,"Defect","peeling","bong tróc"],
[299,9,"Defect","wrinkle","nếp nhăn"],
[300,9,"Defect","crease","nếp gấp"],
[301,9,"Defect","deformation","biến dạng"],
[302,9,"Defect","warpage","cong vênh"],
[303,9,"Defect","misalignment","lệch vị trí"],
[304,9,"Defect","offset","độ lệch"],
[305,9,"Defect","missing part","thiếu chi tiết"],
[306,9,"Defect","wrong part","sai chi tiết"],

[307,10,"Defect","incomplete cut","cắt không hoàn toàn"],
[308,10,"Defect","under-cut","cắt thiếu"],
[309,10,"Defect","over-cut","cắt quá"],
[310,10,"Defect","oozing","tràn keo"],
[311,10,"Defect","excess adhesive","keo dư"],
[312,10,"Defect","insufficient adhesive","thiếu keo"],
[313,10,"Defect","adhesive residue","keo tồn dư"],
[314,10,"Defect","poor adhesion","độ bám dính kém"],
[315,10,"Defect","lifting","hở/bong mép"],
[316,10,"Defect","color mismatch","không khớp màu"],
[317,10,"Defect","discoloration","biến màu"],
[318,10,"Defect","surface damage","hư hỏng bề mặt"],
[319,10,"Defect","edge damage","hư hỏng cạnh"],
[320,10,"Defect","dimension out","kích thước ngoài tiêu chuẩn"],
[321,10,"Defect","abnormality","bất thường"],
[322,10,"Defect","failure","hỏng/lỗi chức năng"],
[323,10,"Defect","false reject","loại nhầm hàng tốt"],
[324,10,"Defect","false accept","chấp nhận nhầm hàng lỗi"],
[325,10,"Defect","escape defect","lỗi lọt"],
[326,10,"Defect","repeated defect","lỗi lặp lại"],
[327,10,"Defect","intermittent defect","lỗi gián đoạn"],
[328,10,"Defect","random defect","lỗi ngẫu nhiên"],
[329,10,"Defect","systematic defect","lỗi có hệ thống"],
[330,10,"Defect","detect a defect","phát hiện lỗi"],
[331,10,"Defect","reproduce the defect","tái hiện lỗi"],
[332,10,"Defect","isolate the defect","cô lập lỗi"],
[333,10,"Defect","classify the defect","phân loại lỗi"],
[334,10,"Defect","contain the defect","khoanh vùng/ngăn lỗi lan rộng"],
[335,10,"Defect","reduce the defect rate","giảm tỷ lệ lỗi"],
[336,10,"Defect","eliminate the defect","loại bỏ lỗi"],
[337,10,"Defect","prevent recurrence","ngăn tái diễn"],
[338,10,"Defect","trace the defect","truy vết lỗi"],
[339,10,"Defect","inspect visually","kiểm tra ngoại quan"],
[340,10,"Defect","reject the part","loại bỏ sản phẩm lỗi"],

[341,11,"Quality","quality","chất lượng"],
[342,11,"Quality","quality control","kiểm soát chất lượng"],
[343,11,"Quality","quality assurance","đảm bảo chất lượng"],
[344,11,"Quality","quality standard","tiêu chuẩn chất lượng"],
[345,11,"Quality","quality requirement","yêu cầu chất lượng"],
[346,11,"Quality","quality criteria","tiêu chí chất lượng"],
[347,11,"Quality","quality target","mục tiêu chất lượng"],
[348,11,"Quality","quality level","mức chất lượng"],
[349,11,"Quality","quality issue","vấn đề chất lượng"],
[350,11,"Quality","quality risk","rủi ro chất lượng"],
[351,11,"Quality","quality gate","cổng kiểm soát chất lượng"],
[352,11,"Quality","inspection","kiểm tra"],
[353,11,"Quality","visual inspection","kiểm tra ngoại quan"],
[354,11,"Quality","dimensional inspection","kiểm tra kích thước"],
[355,11,"Quality","functional test","kiểm tra chức năng"],
[356,11,"Quality","sampling inspection","kiểm tra lấy mẫu"],
[357,11,"Quality","100% inspection","kiểm tra 100%"],
[358,11,"Quality","incoming inspection","kiểm tra đầu vào"],
[359,11,"Quality","outgoing inspection","kiểm tra đầu ra"],
[360,11,"Quality","final inspection","kiểm tra cuối"],
[361,11,"Quality","acceptance criteria","tiêu chí chấp nhận"],
[362,11,"Quality","inspection standard","tiêu chuẩn kiểm tra"],
[363,11,"Quality","inspection method","phương pháp kiểm tra"],
[364,11,"Quality","inspection frequency","tần suất kiểm tra"],
[365,11,"Quality","sample size","cỡ mẫu"],
[366,11,"Quality","AQL","mức chất lượng chấp nhận AQL"],
[367,11,"Quality","pass","kết quả đạt"],
[368,11,"Quality","fail","kết quả không đạt"],
[369,11,"Quality","nonconformance","sự không phù hợp"],
[370,11,"Quality","nonconforming product","sản phẩm không phù hợp"],
[371,11,"Quality","NCR","báo cáo không phù hợp"],
[372,11,"Quality","quality alert","cảnh báo chất lượng"],
[373,11,"Quality","quality hold","giữ hàng do chất lượng"],

[374,12,"Quality","quarantine area","khu vực cách ly"],
[375,12,"Quality","sorting","phân loại/sàng lọc"],
[376,12,"Quality","reinspection","kiểm tra lại"],
[377,12,"Quality","rework instruction","hướng dẫn sửa hàng"],
[378,12,"Quality","disposition","quyết định xử lý hàng"],
[379,12,"Quality","concession","chấp thuận ngoại lệ"],
[380,12,"Quality","deviation approval","phê duyệt sai lệch"],
[381,12,"Quality","traceability","khả năng truy xuất"],
[382,12,"Quality","lot traceability","truy xuất theo lô"],
[383,12,"Quality","record retention","lưu giữ hồ sơ"],
[384,12,"Quality","control plan","kế hoạch kiểm soát"],
[385,12,"Quality","check sheet","phiếu kiểm tra"],
[386,12,"Quality","inspection record","hồ sơ kiểm tra"],
[387,12,"Quality","quality report","báo cáo chất lượng"],
[388,12,"Quality","quality trend","xu hướng chất lượng"],
[389,12,"Quality","quality performance","kết quả chất lượng"],
[390,12,"Quality","customer complaint","khiếu nại khách hàng"],
[391,12,"Quality","customer return","hàng khách trả về"],
[392,12,"Quality","field failure","lỗi ngoài hiện trường"],
[393,12,"Quality","specification limit","giới hạn tiêu chuẩn"],
[394,12,"Quality","measurement system","hệ thống đo lường"],
[395,12,"Quality","gauge","dụng cụ đo"],
[396,12,"Quality","calibration status","trạng thái hiệu chuẩn"],
[397,12,"Quality","measurement accuracy","độ chính xác đo lường"],
[398,12,"Quality","measurement error","sai số đo"],
[399,12,"Quality","measurement uncertainty","độ không đảm bảo đo"],
[400,12,"Quality","audit","đánh giá"],
[401,12,"Quality","internal audit","đánh giá nội bộ"],
[402,12,"Quality","process audit","đánh giá quy trình"],
[403,12,"Quality","product audit","đánh giá sản phẩm"],
[404,12,"Quality","comply with","tuân thủ"],
[405,12,"Quality","meet the requirement","đáp ứng yêu cầu"],
[406,12,"Quality","verify quality","xác minh chất lượng"],

[407,13,"Quality","release the lot","phê duyệt xuất lô"],
[408,13,"Quality","hold the lot","giữ lô hàng"],
[409,13,"Quality","accept the lot","chấp nhận lô hàng"],
[410,13,"Quality","reject the lot","từ chối lô hàng"],
[411,13,"Problem Solving","problem","vấn đề"],
[412,13,"Problem Solving","issue","vấn đề/sự cố"],
[413,13,"Problem Solving","symptom","triệu chứng/biểu hiện"],
[414,13,"Problem Solving","root cause","nguyên nhân gốc"],
[415,13,"Problem Solving","potential cause","nguyên nhân tiềm ẩn"],
[416,13,"Problem Solving","direct cause","nguyên nhân trực tiếp"],
[417,13,"Problem Solving","contributing factor","yếu tố góp phần"],
[418,13,"Problem Solving","failure mechanism","cơ chế lỗi"],
[419,13,"Problem Solving","problem statement","mô tả vấn đề"],
[420,13,"Problem Solving","problem scope","phạm vi vấn đề"],
[421,13,"Problem Solving","impact","tác động"],
[422,13,"Problem Solving","severity","mức độ nghiêm trọng"],
[423,13,"Problem Solving","occurrence","tần suất xảy ra"],
[424,13,"Problem Solving","detection","khả năng phát hiện"],
[425,13,"Problem Solving","containment","biện pháp khoanh vùng"],
[426,13,"Problem Solving","immediate action","hành động tức thời"],
[427,13,"Problem Solving","corrective action","hành động khắc phục"],
[428,13,"Problem Solving","preventive action","hành động phòng ngừa"],
[429,13,"Problem Solving","countermeasure","đối sách"],
[430,13,"Problem Solving","action item","hạng mục hành động"],
[431,13,"Problem Solving","action owner","người phụ trách hành động"],
[432,13,"Problem Solving","due date","hạn hoàn thành"],
[433,13,"Problem Solving","verification","xác minh"],
[434,13,"Problem Solving","validation","xác nhận hiệu lực"],
[435,13,"Problem Solving","effectiveness check","kiểm tra hiệu lực"],
[436,13,"Problem Solving","recurrence","sự tái diễn"],
[437,13,"Problem Solving","lesson learned","bài học kinh nghiệm"],
[438,13,"Problem Solving","5 Why analysis","phân tích 5 Why"],
[439,13,"Problem Solving","fishbone diagram","biểu đồ xương cá"],

[440,14,"Problem Solving","Ishikawa diagram","biểu đồ Ishikawa"],
[441,14,"Problem Solving","4M analysis","phân tích 4M"],
[442,14,"Problem Solving","6M analysis","phân tích 6M"],
[443,14,"Problem Solving","fault tree analysis","phân tích cây lỗi"],
[444,14,"Problem Solving","FMEA","phân tích sai hỏng và tác động"],
[445,14,"Problem Solving","risk priority number","chỉ số ưu tiên rủi ro RPN"],
[446,14,"Problem Solving","8D report","báo cáo 8D"],
[447,14,"Problem Solving","FACA","phân tích lỗi và hành động khắc phục"],
[448,14,"Problem Solving","CAPA","hành động khắc phục và phòng ngừa"],
[449,14,"Problem Solving","hypothesis","giả thuyết"],
[450,14,"Problem Solving","experiment","thí nghiệm"],
[451,14,"Problem Solving","DOE","thiết kế thí nghiệm"],
[452,14,"Problem Solving","control group","nhóm đối chứng"],
[453,14,"Problem Solving","comparison group","nhóm so sánh"],
[454,14,"Problem Solving","evidence","bằng chứng"],
[455,14,"Problem Solving","data point","điểm dữ liệu"],
[456,14,"Problem Solving","correlation","tương quan"],
[457,14,"Problem Solving","causal relationship","quan hệ nhân quả"],
[458,14,"Problem Solving","cause-and-effect","nguyên nhân và kết quả"],
[459,14,"Problem Solving","identify the cause","xác định nguyên nhân"],
[460,14,"Problem Solving","investigate the issue","điều tra vấn đề"],
[461,14,"Problem Solving","analyze the data","phân tích dữ liệu"],
[462,14,"Problem Solving","verify the hypothesis","xác minh giả thuyết"],
[463,14,"Problem Solving","rule out a cause","loại trừ một nguyên nhân"],
[464,14,"Problem Solving","narrow down the cause","thu hẹp nguyên nhân"],
[465,14,"Problem Solving","reproduce the issue","tái hiện vấn đề"],
[466,14,"Problem Solving","isolate the variable","cô lập biến số"],
[467,14,"Problem Solving","change one factor at a time","thay đổi từng yếu tố một"],
[468,14,"Problem Solving","compare the results","so sánh kết quả"],
[469,14,"Problem Solving","confirm the root cause","xác nhận nguyên nhân gốc"],
[470,14,"Problem Solving","implement an action","triển khai hành động"],
[471,14,"Problem Solving","verify effectiveness","xác minh hiệu lực"],
[472,14,"Problem Solving","standardize the action","tiêu chuẩn hóa hành động"],

[473,15,"Problem Solving","recurrence prevention","phòng ngừa tái diễn"],
[474,15,"Problem Solving","escalate the issue","nâng cấp/báo cáo vấn đề lên cấp cao hơn"],
[475,15,"Problem Solving","close the action","đóng hành động"],
[476,15,"Problem Solving","follow up on the action","theo dõi hành động"],
[477,15,"Problem Solving","open issue","vấn đề chưa đóng"],
[478,15,"Problem Solving","known issue","vấn đề đã biết"],
[479,15,"Problem Solving","unknown cause","nguyên nhân chưa xác định"],
[480,15,"Problem Solving","problem recurrence","sự tái diễn của vấn đề"],
[481,15,"Data Analysis","data","dữ liệu"],
[482,15,"Data Analysis","dataset","tập dữ liệu"],
[483,15,"Data Analysis","data source","nguồn dữ liệu"],
[484,15,"Data Analysis","data collection","thu thập dữ liệu"],
[485,15,"Data Analysis","data accuracy","độ chính xác dữ liệu"],
[486,15,"Data Analysis","data integrity","tính toàn vẹn dữ liệu"],
[487,15,"Data Analysis","data cleaning","làm sạch dữ liệu"],
[488,15,"Data Analysis","data validation","xác thực dữ liệu"],
[489,15,"Data Analysis","sample","mẫu"],
[490,15,"Data Analysis","number of samples","số lượng mẫu"],
[491,15,"Data Analysis","population","tổng thể"],
[492,15,"Data Analysis","variable","biến số"],
[493,15,"Data Analysis","independent variable","biến độc lập"],
[494,15,"Data Analysis","dependent variable","biến phụ thuộc"],
[495,15,"Data Analysis","categorical data","dữ liệu phân loại"],
[496,15,"Data Analysis","continuous data","dữ liệu liên tục"],
[497,15,"Data Analysis","discrete data","dữ liệu rời rạc"],
[498,15,"Data Analysis","mean","giá trị trung bình"],
[499,15,"Data Analysis","median","trung vị"],
[500,15,"Data Analysis","mode","mốt/giá trị xuất hiện nhiều nhất"],
[501,15,"Data Analysis","minimum","giá trị nhỏ nhất"],
[502,15,"Data Analysis","maximum","giá trị lớn nhất"],
[503,15,"Data Analysis","range","khoảng biến thiên"],
[504,15,"Data Analysis","variance","phương sai"],
[505,15,"Data Analysis","standard deviation","độ lệch chuẩn"],

[506,16,"Data Analysis","percentile","phân vị"],
[507,16,"Data Analysis","trend","xu hướng"],
[508,16,"Data Analysis","pattern","mẫu hình"],
[509,16,"Data Analysis","outlier","giá trị ngoại lai"],
[510,16,"Data Analysis","distribution","phân phối"],
[511,16,"Data Analysis","normal distribution","phân phối chuẩn"],
[512,16,"Data Analysis","histogram","biểu đồ tần suất"],
[513,16,"Data Analysis","bar chart","biểu đồ cột"],
[514,16,"Data Analysis","line chart","biểu đồ đường"],
[515,16,"Data Analysis","scatter plot","biểu đồ phân tán"],
[516,16,"Data Analysis","box plot","biểu đồ hộp"],
[517,16,"Data Analysis","Pareto chart","biểu đồ Pareto"],
[518,16,"Data Analysis","control chart","biểu đồ kiểm soát"],
[519,16,"Data Analysis","run chart","biểu đồ theo thời gian"],
[520,16,"Data Analysis","correlation coefficient","hệ số tương quan"],
[521,16,"Data Analysis","regression","hồi quy"],
[522,16,"Data Analysis","slope","độ dốc"],
[523,16,"Data Analysis","intercept","hệ số chặn"],
[524,16,"Data Analysis","confidence interval","khoảng tin cậy"],
[525,16,"Data Analysis","significance level","mức ý nghĩa"],
[526,16,"Data Analysis","p-value","giá trị p"],
[527,16,"Data Analysis","baseline","đường cơ sở/mức chuẩn ban đầu"],
[528,16,"Data Analysis","benchmark","mốc chuẩn so sánh"],
[529,16,"Data Analysis","before-and-after comparison","so sánh trước và sau"],
[530,16,"Data Analysis","yield trend","xu hướng yield"],
[531,16,"Data Analysis","defect trend","xu hướng lỗi"],
[532,16,"Data Analysis","analyze the trend","phân tích xu hướng"],
[533,16,"Data Analysis","plot the data","vẽ biểu đồ dữ liệu"],
[534,16,"Data Analysis","filter the data","lọc dữ liệu"],
[535,16,"Data Analysis","sort the data","sắp xếp dữ liệu"],
[536,16,"Data Analysis","compare two groups","so sánh hai nhóm"],
[537,16,"Data Analysis","calculate the average","tính giá trị trung bình"],
[538,16,"Data Analysis","identify an outlier","xác định giá trị ngoại lai"],

[539,17,"Data Analysis","interpret the result","diễn giải kết quả"],
[540,17,"Data Analysis","support the conclusion","hỗ trợ kết luận bằng dữ liệu"],
[541,17,"Meeting","meeting","cuộc họp"],
[542,17,"Meeting","agenda","chương trình họp"],
[543,17,"Meeting","meeting objective","mục tiêu cuộc họp"],
[544,17,"Meeting","meeting room","phòng họp"],
[545,17,"Meeting","meeting invite","lời mời họp"],
[546,17,"Meeting","attendee","người tham dự"],
[547,17,"Meeting","participant","người tham gia"],
[548,17,"Meeting","chairperson","chủ trì cuộc họp"],
[549,17,"Meeting","facilitator","người điều phối"],
[550,17,"Meeting","minutes","biên bản họp"],
[551,17,"Meeting","meeting notes","ghi chú cuộc họp"],
[552,17,"Meeting","meeting action","hành động sau cuộc họp"],
[553,17,"Meeting","owner","người phụ trách"],
[554,17,"Meeting","deadline","hạn hoàn thành"],
[555,17,"Meeting","follow-up","theo dõi sau họp"],
[556,17,"Meeting","open point","điểm còn mở"],
[557,17,"Meeting","pending item","hạng mục đang chờ"],
[558,17,"Meeting","key takeaway","điểm chính rút ra"],
[559,17,"Meeting","decision","quyết định"],
[560,17,"Meeting","consensus","sự đồng thuận"],
[561,17,"Meeting","priority","mức ưu tiên"],
[562,17,"Meeting","update","cập nhật"],
[563,17,"Meeting","status update","cập nhật trạng thái"],
[564,17,"Meeting","progress update","cập nhật tiến độ"],
[565,17,"Meeting","blocker","trở ngại"],
[566,17,"Meeting","risk","rủi ro"],
[567,17,"Meeting","next step","bước tiếp theo"],
[568,17,"Meeting","kick-off meeting","họp khởi động"],
[569,17,"Meeting","daily meeting","họp hằng ngày"],
[570,17,"Meeting","weekly meeting","họp hằng tuần"],
[571,17,"Meeting","review meeting","họp rà soát"],

[572,18,"Meeting","customer meeting","họp với khách hàng"],
[573,18,"Meeting","supplier meeting","họp với nhà cung cấp"],
[574,18,"Meeting","join the meeting","tham gia cuộc họp"],
[575,18,"Meeting","start the meeting","bắt đầu cuộc họp"],
[576,18,"Meeting","open the meeting","mở đầu cuộc họp"],
[577,18,"Meeting","share an update","chia sẻ cập nhật"],
[578,18,"Meeting","raise a concern","nêu quan ngại"],
[579,18,"Meeting","ask for clarification","yêu cầu làm rõ"],
[580,18,"Meeting","clarify the point","làm rõ vấn đề"],
[581,18,"Meeting","summarize the discussion","tóm tắt thảo luận"],
[582,18,"Meeting","agree on the action","thống nhất hành động"],
[583,18,"Meeting","assign an owner","chỉ định người phụ trách"],
[584,18,"Meeting","set a deadline","đặt thời hạn"],
[585,18,"Meeting","follow up after the meeting","theo dõi sau cuộc họp"],
[586,18,"Meeting","reschedule the meeting","đổi lịch họp"],
[587,18,"Meeting","cancel the meeting","hủy cuộc họp"],
[588,18,"Meeting","run over time","họp quá giờ"],
[589,18,"Meeting","keep the meeting on track","giữ cuộc họp đúng trọng tâm"],
[590,18,"Meeting","Let me give a quick update.","Để tôi cập nhật nhanh."],
[591,18,"Meeting","Could you clarify that point?","Bạn có thể làm rõ điểm đó không?"],
[592,18,"Meeting","I agree with this approach.","Tôi đồng ý với cách tiếp cận này."],
[593,18,"Meeting","We need to close this action.","Chúng ta cần đóng hành động này."],
[594,18,"Meeting","What is the next step?","Bước tiếp theo là gì?"],
[595,18,"Meeting","Let's summarize the key points.","Hãy tóm tắt các điểm chính."],
[596,18,"Email","email","thư điện tử"],
[597,18,"Email","subject line","dòng tiêu đề"],
[598,18,"Email","recipient","người nhận"],
[599,18,"Email","sender","người gửi"],
[600,18,"Email","attachment","tệp đính kèm"],
[601,18,"Email","email thread","chuỗi email"],
[602,18,"Email","reply","phản hồi"],
[603,18,"Email","reply all","trả lời tất cả"],
[604,18,"Email","forward","chuyển tiếp"],

[605,19,"Email","cc","gửi đồng thời cho người liên quan"],
[606,19,"Email","bcc","gửi ẩn danh sách người nhận"],
[607,19,"Email","inbox","hộp thư đến"],
[608,19,"Email","draft","bản nháp"],
[609,19,"Email","follow-up email","email theo dõi"],
[610,19,"Email","reminder email","email nhắc việc"],
[611,19,"Email","confirmation email","email xác nhận"],
[612,19,"Email","request","yêu cầu"],
[613,19,"Email","inquiry","thắc mắc/yêu cầu thông tin"],
[614,19,"Email","response","phản hồi"],
[615,19,"Email","feedback","phản hồi/góp ý"],
[616,19,"Email","email update","cập nhật qua email"],
[617,19,"Email","clarification","sự làm rõ"],
[618,19,"Email","approval","phê duyệt"],
[619,19,"Email","reference","tài liệu/thông tin tham chiếu"],
[620,19,"Email","response deadline","hạn phản hồi"],
[621,19,"Email","Please find attached...","Vui lòng xem tệp đính kèm..."],
[622,19,"Email","For your reference,...","Để bạn tham khảo,..."],
[623,19,"Email","For your information,...","Để bạn nắm thông tin,..."],
[624,19,"Email","As discussed,...","Như đã trao đổi,..."],
[625,19,"Email","As mentioned below,...","Như đã đề cập bên dưới,..."],
[626,19,"Email","Regarding the issue,...","Liên quan đến vấn đề..."],
[627,19,"Email","With regard to...","Liên quan đến..."],
[628,19,"Email","Could you please confirm...?","Bạn vui lòng xác nhận... được không?"],
[629,19,"Email","Could you please check...?","Bạn vui lòng kiểm tra... được không?"],
[630,19,"Email","Please let me know...","Vui lòng cho tôi biết..."],
[631,19,"Email","Please advise.","Vui lòng tư vấn/cho ý kiến."],
[632,19,"Email","Please review and confirm.","Vui lòng xem xét và xác nhận."],
[633,19,"Email","Please see the details below.","Vui lòng xem chi tiết bên dưới."],
[634,19,"Email","Thank you for your support.","Cảm ơn bạn đã hỗ trợ."],
[635,19,"Email","Thank you for the update.","Cảm ơn bạn đã cập nhật."],
[636,19,"Email","Sorry for the late reply.","Xin lỗi vì phản hồi muộn."],
[637,19,"Email","Sorry for the inconvenience.","Xin lỗi vì sự bất tiện."],

[638,20,"Email","We have completed the action.","Chúng tôi đã hoàn thành hành động."],
[639,20,"Email","We are still investigating the issue.","Chúng tôi vẫn đang điều tra vấn đề."],
[640,20,"Email","We will update you by tomorrow.","Chúng tôi sẽ cập nhật cho bạn trước ngày mai."],
[641,20,"Email","The issue has been resolved.","Vấn đề đã được giải quyết."],
[642,20,"Email","The result is attached for your review.","Kết quả được đính kèm để bạn xem xét."],
[643,20,"Email","Could you share more details?","Bạn có thể chia sẻ thêm chi tiết không?"],
[644,20,"Email","Could you support this request?","Bạn có thể hỗ trợ yêu cầu này không?"],
[645,20,"Email","We need your approval.","Chúng tôi cần phê duyệt của bạn."],
[646,20,"Email","I will follow up on this action.","Tôi sẽ theo dõi hành động này."],
[647,20,"Email","Let me clarify the situation.","Để tôi làm rõ tình hình."],
[648,20,"Email","Feel free to contact me if you have any questions.","Hãy liên hệ với tôi nếu bạn có câu hỏi."],
[649,20,"Email","Best regards","Trân trọng"],
[650,20,"Email","Kind regards","Trân trọng"],
[651,20,"Presentation","presentation","bài thuyết trình"],
[652,20,"Presentation","slide","trang trình chiếu"],
[653,20,"Presentation","title slide","trang tiêu đề"],
[654,20,"Presentation","agenda slide","trang nội dung/chương trình"],
[655,20,"Presentation","summary slide","trang tóm tắt"],
[656,20,"Presentation","chart","biểu đồ"],
[657,20,"Presentation","graph","đồ thị"],
[658,20,"Presentation","table","bảng"],
[659,20,"Presentation","figure","hình minh họa"],
[660,20,"Presentation","diagram","sơ đồ"],
[661,20,"Presentation","flowchart","lưu đồ"],
[662,20,"Presentation","timeline","dòng thời gian"],
[663,20,"Presentation","key message","thông điệp chính"],
[664,20,"Presentation","key finding","phát hiện chính"],
[665,20,"Presentation","background","bối cảnh"],
[666,20,"Presentation","objective","mục tiêu"],
[667,20,"Presentation","scope","phạm vi"],
[668,20,"Presentation","methodology","phương pháp"],
[669,20,"Presentation","result","kết quả"],
[670,20,"Presentation","conclusion","kết luận"],

[671,21,"Presentation","recommendation","khuyến nghị"],
[672,21,"Presentation","next-step recommendation","khuyến nghị bước tiếp theo"],
[673,21,"Presentation","supporting data","dữ liệu hỗ trợ"],
[674,21,"Presentation","visual evidence","bằng chứng trực quan"],
[675,21,"Presentation","data trend","xu hướng dữ liệu"],
[676,21,"Presentation","comparison","so sánh"],
[677,21,"Presentation","highlight","điểm nhấn"],
[678,21,"Presentation","takeaway","điểm cần ghi nhớ"],
[679,21,"Presentation","present the data","trình bày dữ liệu"],
[680,21,"Presentation","explain the result","giải thích kết quả"],
[681,21,"Presentation","highlight the difference","nhấn mạnh sự khác biệt"],
[682,21,"Presentation","compare performance results","so sánh kết quả hiệu suất"],
[683,21,"Presentation","walk through the slide","trình bày lần lượt nội dung trang"],
[684,21,"Presentation","move to the next slide","chuyển sang trang tiếp theo"],
[685,21,"Presentation","summarize the finding","tóm tắt phát hiện"],
[686,21,"Presentation","substantiate the conclusion","củng cố kết luận bằng bằng chứng"],
[687,21,"Presentation","address a question","trả lời/xử lý câu hỏi"],
[688,21,"Presentation","Let me start with the background.","Tôi xin bắt đầu với phần bối cảnh."],
[689,21,"Presentation","The objective of this study is...","Mục tiêu của nghiên cứu này là..."],
[690,21,"Presentation","This slide shows...","Trang này cho thấy..."],
[691,21,"Presentation","As you can see,...","Như bạn có thể thấy,..."],
[692,21,"Presentation","The key point is...","Điểm chính là..."],
[693,21,"Presentation","There is a clear difference between...","Có sự khác biệt rõ ràng giữa..."],
[694,21,"Presentation","The defect rate increased significantly.","Tỷ lệ lỗi tăng đáng kể."],
[695,21,"Presentation","The result improved after the change.","Kết quả được cải thiện sau thay đổi."],
[696,21,"Presentation","Based on the data,...","Dựa trên dữ liệu,..."],
[697,21,"Presentation","This result indicates that...","Kết quả này cho thấy rằng..."],
[698,21,"Presentation","We confirmed that...","Chúng tôi xác nhận rằng..."],
[699,21,"Presentation","The root cause was...","Nguyên nhân gốc là..."],
[700,21,"Presentation","The action was effective.","Hành động có hiệu quả."],
[701,21,"Presentation","In conclusion,...","Tóm lại,..."],
[702,21,"Presentation","Our recommendation is...","Khuyến nghị của chúng tôi là..."],
[703,21,"Presentation","The next step is...","Bước tiếp theo là..."],

[704,22,"Presentation","Thank you for your attention.","Cảm ơn bạn đã chú ý lắng nghe."],
[705,22,"Presentation","Do you have any questions?","Bạn có câu hỏi nào không?"],
[706,22,"Customer Communication","customer","khách hàng"],
[707,22,"Customer Communication","customer requirement","yêu cầu khách hàng"],
[708,22,"Customer Communication","customer expectation","kỳ vọng khách hàng"],
[709,22,"Customer Communication","customer feedback","phản hồi khách hàng"],
[710,22,"Customer Communication","customer concern","mối quan ngại của khách hàng"],
[711,22,"Customer Communication","complaint case","trường hợp khiếu nại"],
[712,22,"Customer Communication","customer request","yêu cầu của khách hàng"],
[713,22,"Customer Communication","customer approval","phê duyệt của khách hàng"],
[714,22,"Customer Communication","customer visit","chuyến thăm của khách hàng"],
[715,22,"Customer Communication","customer audit","đánh giá của khách hàng"],
[716,22,"Customer Communication","customer report","báo cáo gửi khách hàng"],
[717,22,"Customer Communication","response time","thời gian phản hồi"],
[718,22,"Customer Communication","commitment","cam kết"],
[719,22,"Customer Communication","delivery date","ngày giao hàng"],
[720,22,"Customer Communication","response timeline","tiến độ phản hồi"],
[721,22,"Customer Communication","status","trạng thái"],
[722,22,"Customer Communication","progress","tiến độ"],
[723,22,"Customer Communication","customer-facing risk","rủi ro ảnh hưởng tới khách hàng"],
[724,22,"Customer Communication","customer impact","tác động tới khách hàng"],
[725,22,"Customer Communication","containment action","hành động khoanh vùng"],
[726,22,"Customer Communication","corrective action plan","kế hoạch hành động khắc phục"],
[727,22,"Customer Communication","root cause analysis","phân tích nguyên nhân gốc"],
[728,22,"Customer Communication","verification result","kết quả xác minh"],
[729,22,"Customer Communication","supporting evidence","bằng chứng hỗ trợ"],
[730,22,"Customer Communication","sample result","kết quả mẫu"],
[731,22,"Customer Communication","mass production result","kết quả sản xuất hàng loạt"],
[732,22,"Customer Communication","provide an update","cung cấp cập nhật"],
[733,22,"Customer Communication","respond promptly","phản hồi nhanh chóng"],
[734,22,"Customer Communication","clarify the requirement","làm rõ yêu cầu"],
[735,22,"Customer Communication","confirm the timeline","xác nhận tiến độ"],
[736,22,"Customer Communication","share the evidence","chia sẻ bằng chứng"],

[737,23,"Customer Communication","explain the cause","giải thích nguyên nhân"],
[738,23,"Customer Communication","propose an action","đề xuất hành động"],
[739,23,"Customer Communication","commit to a deadline","cam kết thời hạn"],
[740,23,"Customer Communication","manage expectations","quản lý kỳ vọng"],
[741,23,"Customer Communication","address the concern","xử lý mối quan ngại"],
[742,23,"Customer Communication","We understand your concern.","Chúng tôi hiểu mối quan ngại của bạn."],
[743,23,"Customer Communication","Thank you for bringing this to our attention.","Cảm ơn bạn đã thông báo vấn đề này cho chúng tôi."],
[744,23,"Customer Communication","We are investigating the issue.","Chúng tôi đang điều tra vấn đề."],
[745,23,"Customer Communication","We have implemented containment action.","Chúng tôi đã triển khai hành động khoanh vùng."],
[746,23,"Customer Communication","We confirmed the root cause.","Chúng tôi đã xác nhận nguyên nhân gốc."],
[747,23,"Customer Communication","We have completed the corrective action.","Chúng tôi đã hoàn thành hành động khắc phục."],
[748,23,"Customer Communication","The issue is under control.","Vấn đề đang được kiểm soát."],
[749,23,"Customer Communication","There is no impact on shipped products.","Không có ảnh hưởng đến sản phẩm đã giao."],
[750,23,"Customer Communication","We will provide the next update tomorrow.","Chúng tôi sẽ cập nhật tiếp vào ngày mai."],
[751,23,"Customer Communication","Please see the attached evidence.","Vui lòng xem bằng chứng đính kèm."],
[752,23,"Customer Communication","We apologize for the inconvenience.","Chúng tôi xin lỗi vì sự bất tiện."],
[753,23,"Customer Communication","We appreciate your patience.","Chúng tôi cảm ơn sự kiên nhẫn của bạn."],
[754,23,"Customer Communication","Thank you for your understanding.","Cảm ơn sự thông cảm của bạn."],
[755,23,"Customer Communication","Could you confirm your requirement?","Bạn có thể xác nhận yêu cầu của mình không?"],
[756,23,"Customer Communication","Could you provide a reference sample?","Bạn có thể cung cấp mẫu tham chiếu không?"],
[757,23,"Customer Communication","We would like to propose the following action.","Chúng tôi muốn đề xuất hành động sau."],
[758,23,"Customer Communication","We expect to complete this by Friday.","Chúng tôi dự kiến hoàn thành việc này trước thứ Sáu."],
[759,23,"Customer Communication","Please let us know if this meets your expectation.","Vui lòng cho chúng tôi biết liệu điều này có đáp ứng kỳ vọng của bạn không."],
[760,23,"Customer Communication","customer response","phản hồi cho khách hàng"],
[761,23,"Safety & EHS","safety","an toàn"],
[762,23,"Safety & EHS","hazard","mối nguy"],
[763,23,"Safety & EHS","risk assessment","đánh giá rủi ro"],
[764,23,"Safety & EHS","PPE","trang bị bảo hộ cá nhân"],
[765,23,"Safety & EHS","safety glasses","kính bảo hộ"],
[766,23,"Safety & EHS","safety shoes","giày bảo hộ"],
[767,23,"Safety & EHS","protective gloves","găng tay bảo hộ"],
[768,23,"Safety & EHS","face shield","tấm che mặt"],
[769,23,"Safety & EHS","hearing protection","bảo vệ thính giác"],

[770,24,"Safety & EHS","chemical exposure","phơi nhiễm hóa chất"],
[771,24,"Safety & EHS","safety data sheet","phiếu an toàn hóa chất SDS"],
[772,24,"Safety & EHS","spill","sự cố tràn đổ"],
[773,24,"Safety & EHS","emergency response","ứng phó khẩn cấp"],
[774,24,"Safety & EHS","evacuation","sơ tán"],
[775,24,"Safety & EHS","fire extinguisher","bình chữa cháy"],
[776,24,"Safety & EHS","emergency exit","lối thoát hiểm"],
[777,24,"Safety & EHS","lockout tagout","khóa và gắn thẻ an toàn LOTO"],
[778,24,"Safety & EHS","machine guarding","che chắn an toàn máy"],
[779,24,"Safety & EHS","near miss","sự cố suýt xảy ra"],
[780,24,"Safety & EHS","incident","sự cố an toàn"],
[781,24,"Safety & EHS","accident","tai nạn"],
[782,24,"Safety & EHS","unsafe condition","điều kiện không an toàn"],
[783,24,"Safety & EHS","unsafe act","hành vi không an toàn"],
[784,24,"Safety & EHS","housekeeping","duy trì vệ sinh/ngăn nắp nơi làm việc"],
[785,24,"Safety & EHS","waste segregation","phân loại chất thải"],
[786,24,"Safety & EHS","hazardous waste","chất thải nguy hại"],
[787,24,"Safety & EHS","environmental impact","tác động môi trường"],
[788,24,"Safety & EHS","energy consumption","tiêu thụ năng lượng"],
[789,24,"Safety & EHS","water consumption","tiêu thụ nước"],
[790,24,"Safety & EHS","report a hazard","báo cáo mối nguy"],
[791,24,"Safety & EHS","wear PPE","mang trang bị bảo hộ"],
[792,24,"Safety & EHS","follow safety rules","tuân thủ quy tắc an toàn"],
[793,24,"Safety & EHS","stop unsafe work","dừng công việc không an toàn"],
[794,24,"Safety & EHS","isolate the energy source","cô lập nguồn năng lượng"],
[795,24,"Safety & EHS","clean up the spill","xử lý/làm sạch tràn đổ"],
[796,24,"Safety & EHS","evacuate the area","sơ tán khỏi khu vực"],
[797,24,"Safety & EHS","conduct a safety check","thực hiện kiểm tra an toàn"],
[798,24,"Safety & EHS","prevent an accident","ngăn ngừa tai nạn"],
[799,24,"Safety & EHS","work safely","làm việc an toàn"],
[800,24,"Safety & EHS","zero accident","không tai nạn"],
[801,24,"Maintenance","maintenance","bảo trì"],
[802,24,"Maintenance","preventive maintenance","bảo trì phòng ngừa"],

[803,25,"Maintenance","corrective maintenance","bảo trì sửa chữa"],
[804,25,"Maintenance","predictive maintenance","bảo trì dự đoán"],
[805,25,"Maintenance","breakdown","hỏng máy"],
[806,25,"Maintenance","machine failure","sự cố máy"],
[807,25,"Maintenance","maintenance schedule","lịch bảo trì"],
[808,25,"Maintenance","maintenance plan","kế hoạch bảo trì"],
[809,25,"Maintenance","maintenance record","hồ sơ bảo trì"],
[810,25,"Maintenance","maintenance checklist","danh sách kiểm tra bảo trì"],
[811,25,"Maintenance","spare part","phụ tùng thay thế"],
[812,25,"Maintenance","critical spare part","phụ tùng quan trọng"],
[813,25,"Maintenance","service life","tuổi thọ sử dụng"],
[814,25,"Maintenance","wear and tear","hao mòn tự nhiên"],
[815,25,"Maintenance","lubrication","bôi trơn"],
[816,25,"Maintenance","alignment","căn chỉnh"],
[817,25,"Maintenance","calibration","hiệu chuẩn"],
[818,25,"Maintenance","inspection interval","chu kỳ kiểm tra"],
[819,25,"Maintenance","replacement interval","chu kỳ thay thế"],
[820,25,"Maintenance","failure history","lịch sử hỏng hóc"],
[821,25,"Maintenance","mean time between failures","thời gian trung bình giữa hai lần hỏng MTBF"],
[822,25,"Maintenance","mean time to repair","thời gian trung bình sửa chữa MTTR"],
[823,25,"Maintenance","maintenance downtime","thời gian dừng do bảo trì"],
[824,25,"Maintenance","service engineer","kỹ sư dịch vụ"],
[825,25,"Maintenance","repair technician","kỹ thuật viên sửa chữa"],
[826,25,"Maintenance","maintenance tool","dụng cụ bảo trì"],
[827,25,"Maintenance","troubleshooting guide","hướng dẫn xử lý sự cố"],
[828,25,"Maintenance","repair the machine","sửa máy"],
[829,25,"Maintenance","replace a worn part","thay linh kiện bị mòn"],
[830,25,"Maintenance","perform preventive maintenance","thực hiện bảo trì phòng ngừa"],
[831,25,"Maintenance","check for wear","kiểm tra độ mòn"],
[832,25,"Maintenance","clean the sensor","vệ sinh cảm biến"],
[833,25,"Maintenance","lubricate the bearing","bôi trơn vòng bi"],
[834,25,"Maintenance","align the shaft","căn chỉnh trục"],
[835,25,"Maintenance","calibrate the gauge","hiệu chuẩn dụng cụ đo"],

[836,26,"Maintenance","restore the machine","khôi phục máy"],
[837,26,"Maintenance","return to service","đưa máy trở lại hoạt động"],
[838,26,"Maintenance","record the maintenance","ghi nhận bảo trì"],
[839,26,"Maintenance","schedule maintenance","lập lịch bảo trì"],
[840,26,"Maintenance","reduce breakdowns","giảm hỏng máy"],
[841,26,"Lean & Continuous Improvement","continuous improvement","cải tiến liên tục"],
[842,26,"Lean & Continuous Improvement","Kaizen","cải tiến Kaizen"],
[843,26,"Lean & Continuous Improvement","lean manufacturing","sản xuất tinh gọn"],
[844,26,"Lean & Continuous Improvement","waste","lãng phí"],
[845,26,"Lean & Continuous Improvement","overproduction","sản xuất thừa"],
[846,26,"Lean & Continuous Improvement","waiting","chờ đợi"],
[847,26,"Lean & Continuous Improvement","transportation waste","lãng phí vận chuyển"],
[848,26,"Lean & Continuous Improvement","overprocessing","gia công/xử lý thừa"],
[849,26,"Lean & Continuous Improvement","inventory waste","lãng phí tồn kho"],
[850,26,"Lean & Continuous Improvement","motion waste","lãng phí thao tác/di chuyển"],
[851,26,"Lean & Continuous Improvement","defect waste","lãng phí do lỗi"],
[852,26,"Lean & Continuous Improvement","unused talent","lãng phí năng lực con người"],
[853,26,"Lean & Continuous Improvement","value-added activity","hoạt động tạo giá trị"],
[854,26,"Lean & Continuous Improvement","non-value-added activity","hoạt động không tạo giá trị"],
[855,26,"Lean & Continuous Improvement","5S","phương pháp 5S"],
[856,26,"Lean & Continuous Improvement","Sort","Sàng lọc"],
[857,26,"Lean & Continuous Improvement","Set in order","Sắp xếp"],
[858,26,"Lean & Continuous Improvement","Shine","Sạch sẽ"],
[859,26,"Lean & Continuous Improvement","Standardize","Săn sóc/tiêu chuẩn hóa"],
[860,26,"Lean & Continuous Improvement","Sustain","Sẵn sàng/duy trì"],
[861,26,"Lean & Continuous Improvement","visual management","quản lý trực quan"],
[862,26,"Lean & Continuous Improvement","standard work","công việc tiêu chuẩn"],
[863,26,"Lean & Continuous Improvement","one-piece flow","dòng chảy một sản phẩm"],
[864,26,"Lean & Continuous Improvement","pull system","hệ thống kéo"],
[865,26,"Lean & Continuous Improvement","Kanban","hệ thống Kanban"],
[866,26,"Lean & Continuous Improvement","poka-yoke","chống sai lỗi"],
[867,26,"Lean & Continuous Improvement","SMED","chuyển đổi nhanh SMED"],
[868,26,"Lean & Continuous Improvement","OEE","hiệu suất thiết bị tổng thể OEE"],

[869,27,"Lean & Continuous Improvement","value stream mapping","sơ đồ dòng giá trị"],
[870,27,"Lean & Continuous Improvement","Gemba","hiện trường Gemba"],
[871,27,"Lean & Continuous Improvement","improvement idea","ý tưởng cải tiến"],
[872,27,"Lean & Continuous Improvement","reduce waste","giảm lãng phí"],
[873,27,"Lean & Continuous Improvement","simplify the process","đơn giản hóa quy trình"],
[874,27,"Lean & Continuous Improvement","eliminate unnecessary steps","loại bỏ bước không cần thiết"],
[875,27,"Lean & Continuous Improvement","standardize the work","tiêu chuẩn hóa công việc"],
[876,27,"Lean & Continuous Improvement","improve flow","cải thiện dòng chảy"],
[877,27,"Lean & Continuous Improvement","reduce changeover time","giảm thời gian chuyển đổi"],
[878,27,"Lean & Continuous Improvement","prevent mistakes","ngăn ngừa sai lỗi"],
[879,27,"Lean & Continuous Improvement","sustain the improvement","duy trì cải tiến"],
[880,27,"Lean & Continuous Improvement","measure the benefit","đo lường lợi ích"],
[881,27,"Project Management","project","dự án"],
[882,27,"Project Management","project scope","phạm vi dự án"],
[883,27,"Project Management","project objective","mục tiêu dự án"],
[884,27,"Project Management","project plan","kế hoạch dự án"],
[885,27,"Project Management","project schedule","tiến độ dự án"],
[886,27,"Project Management","milestone","cột mốc"],
[887,27,"Project Management","deliverable","sản phẩm bàn giao"],
[888,27,"Project Management","task","nhiệm vụ"],
[889,27,"Project Management","subtask","nhiệm vụ con"],
[890,27,"Project Management","dependency","sự phụ thuộc"],
[891,27,"Project Management","resource","nguồn lực"],
[892,27,"Project Management","budget","ngân sách"],
[893,27,"Project Management","stakeholder","bên liên quan"],
[894,27,"Project Management","project owner","chủ dự án"],
[895,27,"Project Management","project manager","quản lý dự án"],
[896,27,"Project Management","project team","nhóm dự án"],
[897,27,"Project Management","kick-off","khởi động dự án"],
[898,27,"Project Management","project deadline","hạn dự án"],
[899,27,"Project Management","project timeline","tiến độ dự án"],
[900,27,"Project Management","project status","trạng thái dự án"],
[901,27,"Project Management","project progress","tiến độ dự án"],

[902,28,"Project Management","project risk","rủi ro dự án"],
[903,28,"Project Management","issue log","nhật ký vấn đề"],
[904,28,"Project Management","risk register","danh sách rủi ro"],
[905,28,"Project Management","change request","yêu cầu thay đổi"],
[906,28,"Project Management","scope change","thay đổi phạm vi"],
[907,28,"Project Management","action plan","kế hoạch hành động"],
[908,28,"Project Management","project review","rà soát dự án"],
[909,28,"Project Management","project closure","kết thúc dự án"],
[910,28,"Project Management","project lesson learned","bài học kinh nghiệm của dự án"],
[911,28,"Project Management","plan the project","lập kế hoạch dự án"],
[912,28,"Project Management","define the scope","xác định phạm vi"],
[913,28,"Project Management","assign tasks","phân công nhiệm vụ"],
[914,28,"Project Management","track progress","theo dõi tiến độ"],
[915,28,"Project Management","manage risk","quản lý rủi ro"],
[916,28,"Project Management","update the timeline","cập nhật tiến độ thời gian"],
[917,28,"Project Management","meet the deadline","đáp ứng thời hạn"],
[918,28,"Project Management","escalate a blocker","báo cáo trở ngại lên cấp cao hơn"],
[919,28,"Project Management","complete the milestone","hoàn thành cột mốc"],
[920,28,"Project Management","close the project","kết thúc dự án"],
[921,28,"Supplier Quality","supplier","nhà cung cấp"],
[922,28,"Supplier Quality","supplier quality","chất lượng nhà cung cấp"],
[923,28,"Supplier Quality","supplier performance","kết quả hoạt động nhà cung cấp"],
[924,28,"Supplier Quality","supplier evaluation","đánh giá nhà cung cấp"],
[925,28,"Supplier Quality","supplier audit","đánh giá nhà cung cấp tại chỗ"],
[926,28,"Supplier Quality","approved supplier","nhà cung cấp được phê duyệt"],
[927,28,"Supplier Quality","supplier list","danh sách nhà cung cấp"],
[928,28,"Supplier Quality","purchase order","đơn đặt hàng"],
[929,28,"Supplier Quality","incoming lot","lô hàng đầu vào"],
[930,28,"Supplier Quality","incoming quality","chất lượng đầu vào"],
[931,28,"Supplier Quality","supplier COA","COA của nhà cung cấp"],
[932,28,"Supplier Quality","certificate of conformity","chứng nhận phù hợp COC"],
[933,28,"Supplier Quality","supplier material specification","đặc tính vật liệu của nhà cung cấp"],
[934,28,"Supplier Quality","supplier change","thay đổi từ nhà cung cấp"],

[935,29,"Supplier Quality","process change notification","thông báo thay đổi quy trình"],
[936,29,"Supplier Quality","supplier complaint","khiếu nại nhà cung cấp"],
[937,29,"Supplier Quality","supplier corrective action","hành động khắc phục của nhà cung cấp"],
[938,29,"Supplier Quality","SCAR","yêu cầu hành động khắc phục nhà cung cấp"],
[939,29,"Supplier Quality","8D response","phản hồi 8D"],
[940,29,"Supplier Quality","supplier containment","hành động khoanh vùng của nhà cung cấp"],
[941,29,"Supplier Quality","replacement lot","lô thay thế"],
[942,29,"Supplier Quality","return material","trả vật liệu"],
[943,29,"Supplier Quality","material rejection","từ chối vật liệu"],
[944,29,"Supplier Quality","supplier defect","lỗi từ nhà cung cấp"],
[945,29,"Supplier Quality","lot-to-lot variation","biến động giữa các lô"],
[946,29,"Supplier Quality","quality agreement","thỏa thuận chất lượng"],
[947,29,"Supplier Quality","supplier lead time","thời gian cung ứng của nhà cung cấp"],
[948,29,"Supplier Quality","on-time delivery","giao hàng đúng hạn"],
[949,29,"Supplier Quality","supplier capability","năng lực nhà cung cấp"],
[950,29,"Supplier Quality","source inspection","kiểm tra tại nguồn"],
[951,29,"Supplier Quality","qualify a supplier","đánh giá/phê duyệt nhà cung cấp"],
[952,29,"Supplier Quality","request an 8D","yêu cầu báo cáo 8D"],
[953,29,"Supplier Quality","reject the incoming lot","từ chối lô đầu vào"],
[954,29,"Supplier Quality","return the material","trả lại vật liệu"],
[955,29,"Supplier Quality","request replacement","yêu cầu thay thế"],
[956,29,"Supplier Quality","verify supplier action","xác minh hành động nhà cung cấp"],
[957,29,"Supplier Quality","monitor supplier performance","theo dõi kết quả nhà cung cấp"],
[958,29,"Supplier Quality","approve the material","phê duyệt vật liệu"],
[959,29,"Supplier Quality","confirm the change","xác nhận thay đổi"],
[960,29,"Supplier Quality","follow up with the supplier","theo dõi với nhà cung cấp"],
[961,29,"Workplace Communication","communication","giao tiếp"],
[962,29,"Workplace Communication","teamwork","làm việc nhóm"],
[963,29,"Workplace Communication","collaboration","sự hợp tác"],
[964,29,"Workplace Communication","coordination","sự phối hợp"],
[965,29,"Workplace Communication","handover","bàn giao"],
[966,29,"Workplace Communication","instruction","hướng dẫn/chỉ thị"],
[967,29,"Workplace Communication","support request","yêu cầu hỗ trợ"],

[968,30,"Workplace Communication","verbal response","phản hồi bằng lời"],
[969,30,"Workplace Communication","team feedback","phản hồi của nhóm"],
[970,30,"Workplace Communication","verbal clarification","làm rõ bằng lời"],
[971,30,"Workplace Communication","misunderstanding","sự hiểu nhầm"],
[972,30,"Workplace Communication","agreement","sự đồng ý"],
[973,30,"Workplace Communication","disagreement","sự không đồng ý"],
[974,30,"Workplace Communication","task priority","mức ưu tiên công việc"],
[975,30,"Workplace Communication","urgency","mức độ khẩn cấp"],
[976,30,"Workplace Communication","responsibility","trách nhiệm"],
[977,30,"Workplace Communication","ownership","tinh thần/chủ thể chịu trách nhiệm"],
[978,30,"Workplace Communication","support","sự hỗ trợ"],
[979,30,"Workplace Communication","availability","khả năng sẵn sàng"],
[980,30,"Workplace Communication","workload","khối lượng công việc"],
[981,30,"Workplace Communication","coordinate with","phối hợp với"],
[982,30,"Workplace Communication","work with","làm việc với"],
[983,30,"Workplace Communication","follow up with","theo dõi với"],
[984,30,"Workplace Communication","check with","kiểm tra/xác nhận với"],
[985,30,"Workplace Communication","confirm with","xác nhận với"],
[986,30,"Workplace Communication","ask for support","yêu cầu hỗ trợ"],
[987,30,"Workplace Communication","give feedback","đưa ra phản hồi"],
[988,30,"Workplace Communication","share information","chia sẻ thông tin"],
[989,30,"Workplace Communication","keep someone informed","cập nhật thông tin cho ai đó"],
[990,30,"Workplace Communication","hand over the task","bàn giao nhiệm vụ"],
[991,30,"Workplace Communication","Could you help me with this?","Bạn có thể giúp tôi việc này không?"],
[992,30,"Workplace Communication","Could you check this for me?","Bạn có thể kiểm tra việc này giúp tôi không?"],
[993,30,"Workplace Communication","Let me confirm that.","Để tôi xác nhận việc đó."],
[994,30,"Workplace Communication","I will check and get back to you.","Tôi sẽ kiểm tra và phản hồi lại."],
[995,30,"Workplace Communication","I understand your point.","Tôi hiểu ý của bạn."],
[996,30,"Workplace Communication","I have a different view.","Tôi có quan điểm khác."],
[997,30,"Workplace Communication","Could we discuss this briefly?","Chúng ta có thể trao đổi nhanh việc này không?"],
[998,30,"Workplace Communication","This is our top priority.","Đây là ưu tiên cao nhất của chúng ta."],
[999,30,"Workplace Communication","Please keep me updated.","Vui lòng tiếp tục cập nhật cho tôi."],
[1000,30,"Workplace Communication","Thanks for your cooperation.","Cảm ơn sự hợp tác của bạn."]
];

const isSentence = (text) => /[.!?]$/.test(text.trim());

function makeExample(word, meaning) {
  if (isSentence(word)) {
    return {
      example: word,
      exampleVi: meaning,
    };
  }

  return {
    example: `We discussed ${word} during the technical review.`,
    exampleVi: `Chúng tôi đã trao đổi về ${meaning} trong buổi rà soát kỹ thuật.`,
  };
}

export const vocabulary = rows.map(
  ([id, day, topic, word, meaning]) => ({
    id,
    day,
    topic,
    word,
    meaning,
    ...makeExample(word, meaning),
  })
);